version: '2'
services:
  mongodb:
    image: mongo:latest
    container_name: "mongodb"
    environment:
      - MONGO_DATA_DIR=/data/db
      - MONGO_LOG_DIR=/dev/null
    volumes:
      - db_data:/data/db
    ports:
      - 27017:27017
  movies-api:
    build: ./api
    restart: unless-stopped
    depends_on:
      - mongodb
    volumes:
      - ./api:/usr/src/movies-api
      - /usr/src/movies-api/node_modules
    ports:
      - 3030:3030
    environment:
      API_PORT: 3030
      DATABASE_URL: mongodb://mongodb:27017/movies
volumes:
  db_data:
